REFERENCE_LINE_COLOR = "#FFD54F"
REFERENCE_LINE_WIDTH = 2
REFERENCE_LINE_DASH = "dot"

REFERENCE_LINE = {
    "color": REFERENCE_LINE_COLOR,
    "width": REFERENCE_LINE_WIDTH,
    "dash": REFERENCE_LINE_DASH,
}
